import { openPage, until, pause } from './cdp.mjs';
import { writeFile, mkdir } from 'node:fs/promises';
const out = process.argv[2] || 'design/brain/qa/intro';
const base = process.argv[3] || 'http://127.0.0.1:3000';
await mkdir(out, { recursive: true });
const p = await openPage();
await p.send('Page.bringToFront');
await p.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
await p.send('Page.navigate', { url: base });
await until(p, `document.querySelector('[data-brain-home][data-brain-phase=forming]')`);
const started = Date.now();
const shot = async name => writeFile(`${out}/${name}.png`, Buffer.from((await p.send('Page.captureScreenshot')).data, 'base64'));
const state = () => p.evaluate(`({phase:document.querySelector('[data-brain-home]').dataset.brainPhase, ready:document.querySelector('[data-brain-canvas]').dataset.ready, formation:document.querySelector('[data-brain-canvas]').dataset.formation, hidden:document.hidden})`);
for (const ms of [800, 2000, 3500, 5500, 7500, 8600, 9600, 10400, 11600, 13200]) {
  const wait = started + ms - Date.now();
  if (wait > 0) await pause(wait);
  await shot(`t${String(ms).padStart(5, '0')}`);
  console.log(ms, JSON.stringify(await state()));
}
await until(p, `document.querySelector('[data-brain-home][data-brain-phase=still]')`);
await pause(400);
await shot('rest');
await p.evaluate(`scrollTo({top:450,behavior:'instant'})`); await pause(600);
await shot('explore');
console.log('explore', JSON.stringify(await state()));
await p.evaluate(`scrollTo({top:0,behavior:'instant'})`); await pause(400);
await p.evaluate(`Array.from(document.querySelectorAll('[data-brain-home] button')).find(b=>b.textContent.trim()==='Replay').click()`);
await pause(2500); await shot('replay-2500');
console.log('replay', JSON.stringify(await state()));
await p.evaluate(`Array.from(document.querySelectorAll('[data-brain-home] button')).find(b=>b.textContent.trim()==='Skip intro')?.click()`);
await pause(400); await shot('skipped');
console.log('skipped', JSON.stringify(await state()));
await p.close();
